sudo: required
services:
    - docker

before_install:
    - docker build -t roycez96/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true roycez96/react-test npm test

after_success:
    - docker build -t roycez96/multi-client ./client
    - docker build -t roycez96/multi-nginx ./nginx 
    - docker build -t roycez96/multi-server ./server
    - docker build -t roycez96/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those image and push them into docker hub
    - docker push roycez96/multi-client
    - docker push roycez96/multi-nginx
    - docker push roycez96/multi-server
    - docker push roycez96/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-us-east-2-393401277098
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY